// work/react/mmadmins/src/views/Statistics/Account.js
import React, {Component, useState, useCallback, useMemo} from "react";
import {Row, Col, Table, Button, Spin, Form, Select, Input, Radio, DatePicker, message} from "antd";


import service from "../../services/request";
import Api from '../../services/api';
import useAsync from "../../hooks/useAsync";



const _ = window._;
const moment = window.moment;

const {Option} = Select;
const {RangePicker} = DatePicker;

class SearchFormV extends Component {

    disabledDate = (current) => {
        let oneYearAgo = moment().subtract(1, 'days').subtract(1, 'years');
        let yesterday = moment().subtract(1, 'days');
        return current > yesterday || current < oneYearAgo;
    };

    render() {
        const {getFieldDecorator} = this.props.form;
        const {
            PlatForm,
            DateTimeType,
            TimeStartv,
            TimeEndv,
            AccountName,
        } = this.props;

        const dataRange = [TimeStartv, TimeEndv];


        return (
            <Form layout={"inline"}>
                <Form.Item label={"平台："}>
                    {getFieldDecorator("PlatForm", {
                        initialValue: PlatForm
                    })(
                        <Select
                            style={{width: "100px"}}
                            placeholder="请选择"
                        >
                            {
                                window.accountPlatForms && (["全部"].concat(window.accountPlatForms)).map(p => {
                                    console.log(p)
                                    return <Option value={p} key={p}>{p}</Option>
                                })
                            }
                        </Select>
                    )}
                </Form.Item>

                <Form.Item label={"统计方式："}>
                    {
                        getFieldDecorator("DateTimeType", {
                            initialValue: DateTimeType
                        })(
                            <Radio.Group>
                                <Radio value={0}>日</Radio>
                                <Radio value={1}>月</Radio>
                            </Radio.Group>
                        )
                    }
                </Form.Item>

                <Form.Item label={"时间："}>
                    {
                        getFieldDecorator("dateRange", {
                            initialValue: dataRange
                        })(
                            <RangePicker
                                allowClear={false}
                                disabledDate={this.disabledDate}
                                format={"YYYY-MM-DD"}
                            />
                        )
                    }
                </Form.Item>

                <Form.Item label={"账号："}>
                    {
                        getFieldDecorator("AccountName", {
                            initialValue: AccountName
                        })(
                            <Input/>
                        )
                    }
                </Form.Item>

                <Form.Item>
                    <Button
                        size={"small"} type={"primary"}
                        onClick={() => {
                            this.props.search(this.props.form.getFieldsValue());
                            this.props.form.resetFields();
                        }}>查询</Button>
                </Form.Item>
            </Form>
        )
    }
}

const SearchForm = Form.create({
    name: "SearchForm",
})(SearchFormV);

const format = "YYYYMMDD";

export default function Account() {
    const yesterday = moment().subtract(1, 'days');

    const [searchObj, setSearchObj] = useState({
        PlatForm:"全部",
        StatisticsType: 0,
        DateTimeType: 0,
        TimeStartv: yesterday,
        TimeStart: yesterday.format(format),
        TimeEndv: yesterday,
        TimeEnd: yesterday.format(format),
        Page: 1,
        Size: 10,
    });

    const [list, setList] = useState([]);

    const [count, setCount] = useState(0);

    const search = (obj) => {
        setSearchObj({
            ...searchObj,
            PlatForm: obj.PlatForm,
            DateTimeType: obj.DateTimeType,
            TimeStartv: obj.dateRange[0],
            TimeStart: Number(obj.dateRange[0].format(format)),
            TimeEndv: obj.dateRange[1] || yesterday,
            TimeEnd: Number(obj.dateRange[1].format(format)),
            AccountName: obj.AccountName ? obj.AccountName.trim() : "",
        });

        console.log(searchObj)
    };

    const columns = [

        {
            title: "序号",
            dataIndex: "numbers"
        },
        {
            title: "日期",
            dataIndex: "date"
        },
        {
            title: "账号名",
            dataIndex: "accountName"
        },
        {
            title: "平台",
            dataIndex: "platForm"
        },

        {
            title: "文章数",
            dataIndex: "articleCnt"
        },

        {
            title: "阅读数",
            dataIndex: "readCnt"
        },

        {
            title: "平均阅读数",
            dataIndex: "avgReadCnt"
        },

        {
            title: "粉丝数",
            dataIndex: "fansCnt"
        },

        {
            title: "活跃天数",
            dataIndex: "activeCnt"
        },

    ];

    // 筛选，页码，条数改变时，更新账号列表
    const accountsObj = useAsync(async () => {

        const obj = _.omit({
            ...searchObj,
            PlatForm: searchObj.PlatForm === "全部" ? "" : searchObj.PlatForm,
        }, ['TimeStartv', 'TimeEndv']);

        const result = await service({
            url: Api.statistics_account,
            method: 'get',
            params: obj
        });

        if (result) {
            if (result.code === 200) {
                result.data.map(function (v, i) {
                    v.numbers = i + 1 + (searchObj.Page - 1) * searchObj.Size;
                    return v;
                });

                setList(result.data);
                setCount(result.count);
            }
        }

        return result;

    }, [searchObj]);

    const changePage = (page) => {
        setSearchObj({
            ...searchObj,
            Page: page
        })
    };

    const changeSize = (size) => {
        setSearchObj({
            ...searchObj,
            Size: size
        })
    };

    return useMemo(()=>(
        <>
            <Row>
                <Col span={24}>
                    <SearchForm search={search} {...searchObj} />
                </Col>
            </Row>
            <Row>
                <Col span={24}>
                    {
                        accountsObj.loading ?
                            <Spin/> :
                            <Table
                                size="middle"
                                rowKey={(record) => record.numbers}
                                columns={columns}
                                dataSource={list}
                                bordered
                                pagination={{
                                    showQuickJumper: true,
                                    showSizeChanger: true,
                                    current: searchObj.Page,
                                    defaultCurrent: 1,
                                    pageSize: searchObj.Size,
                                    pageSizeOptions: ['10', '15', '20'],
                                    total: count,
                                    showTotal: total => `共 ${total} 条`,
                                    onShowSizeChange: changeSize,
                                    onChange: changePage
                                }}

                            />
                    }
                </Col>
            </Row>
        </>

    ))
}

// vue/lmbback/src/views/statistic/account.vue
<template>
    <div>
        <div class="el-row">
            <div class="el-col" :span="24">
                <div id="sentence_search">
                    <el-form ref="form" :inline="true"
                             label-width="50px"
                             size="small"
                             class="sentence-form">
                        <el-form-item label="平台："
                                      label-width="50">
                            <el-select v-model="PlatForm"
                                       placeholder="全部"
                                       size="small"
                                       style="width:120px"
                            >
                                <el-option
                                        v-for="(item, i) in platformList"
                                        :key="item._id"
                                        :label="item.name"
                                        :value="item.name">
                                </el-option>
                            </el-select>
                        </el-form-item>

                        <el-form-item label="统计方式：" label-width="50">
                            <el-radio-group v-model="DateTimeType"
                                            @change="changeDateType"
                                            style="width:110px">
                                <el-radio :label="0">日</el-radio>
                                <el-radio :label="1">月</el-radio>
                            </el-radio-group>
                        </el-form-item>

                        <el-form-item label="时间：" label-width="50">

                            <el-date-picker
                                    style="width:280px"
                                    size="small"
                                    clear-icon="mclear-icon"
                                    :clearable="false"
                                    :type="DateTimeType===1?'monthrange':'datetimerange'"
                                    start-placeholder="开始时间"
                                    end-placeholder="结束时间"
                                    v-model="dateRange"
                                    :format.sync="formatUI"
                                    :value-format.sync="formatValue"
                                    :picker-options="pickerOptions"
                            ></el-date-picker>

                        </el-form-item>

                        <el-form-item label="账号：" label-width="50">
                            <el-input
                                    style="width:120px"
                                    v-model="AccountName"
                                    placeholder=""></el-input>
                        </el-form-item>

                        <el-form-item>
                            <el-button size="small" type="primary" @click="searchQuery">查询</el-button>
                        </el-form-item>

                        <el-form-item>
                            <el-button size="small" type="primary" @click="exportTaskExcel">导出</el-button>
                        </el-form-item>
                    </el-form>
                </div>
            </div>
        </div>

        <el-row>
            <el-col :span="24">
                <el-table
                        v-loading="loading"
                        :data="list"
                        :border="true"
                        :stripe="true"
                        size="mini"
                        style="width:100%;"
                >
                    <el-table-column
                            label="序号"
                            type="index"
                            width="80"
                            :index="indexMethod"
                    ></el-table-column>

                    <el-table-column
                            prop="date"
                            label="日期"
                            width="150"
                    ></el-table-column>

                    <el-table-column
                            prop="platForm"
                            label="平台"
                            width="150"
                    >
                    </el-table-column>

                    <el-table-column
                            prop="accountName"
                            label="账号名"
                            width="200"
                    ></el-table-column>


                    <el-table-column
                            prop="articleCnt"
                            label="文章数"
                            width="100"
                    >
                    </el-table-column>

                    <el-table-column
                            prop="readCnt"
                            label="阅读数"
                            width="100"
                    >
                    </el-table-column>

                    <el-table-column
                            prop="totleReadCnt"
                            label="总阅读量"
                            width="100"
                    >
                    </el-table-column>

                    <el-table-column
                            prop="fansCnt"
                            label="粉丝数"
                            width="100"
                    >
                    </el-table-column>

                    <el-table-column
                            prop="commentCnt"
                            label="评论数"
                            width="100"
                    >
                    </el-table-column>

                    <el-table-column
                            v-if="DateTimeType===1"
                            prop="activeCnt"
                            label="活跃天数"
                    >
                    </el-table-column>

                </el-table>
            </el-col>
        </el-row>

        <el-row>
            <el-col :span="24">
                <!-- 分页 -->
                <div class="pagination-block">
                    <el-pagination
                            @current-change="search"
                            :current-page.sync="Page"
                            :page-size="Size"
                            layout="prev, pager, next, jumper"
                            :total="count">
                    </el-pagination>
                </div>
            </el-col>
        </el-row>
    </div>
</template>

<script>

    import Vue from "vue";
    import {
        Input,
        Table,
        TableColumn,
        Button,
        Dialog,
        Form,
        FormItem,
        Option,
        Select,
        Pagination,
        Row,
        Col,
        DatePicker,
        Radio,
        RadioGroup,
        Loading

    } from "element-ui";

    import {Api} from "../../utils/api";
    import service from "@/utils/request"

    {
        Vue.use(Table);
        Vue.use(TableColumn);
        Vue.use(Button);
        Vue.use(Dialog);
        Vue.use(Form);
        Vue.use(FormItem);
        Vue.use(Option);
        Vue.use(Select);
        Vue.use(Pagination);
        Vue.use(Row);
        Vue.use(Col);
        Vue.use(Input);
        Vue.use(DatePicker);
        Vue.use(Radio);
        Vue.use(RadioGroup);
        Vue.use(Loading);
    }

    export default {
        name: "statistic-account",
        data: function () {
            let yesterday = moment().subtract(1, 'days').format("YYYYMMDD");

            return {
                // 0 按账号 1 按平台
                StatisticsType: 0,
                //平台
                platformList: [],
                PlatForm: "全部",
                // 时间类型： 0 按日 1 按月
                DateTimeType: 0,
                formatValue: "yyyyMMdd",
                formatUI:"yyyy-MM-dd",

                //
                dateRange: [yesterday, yesterday],
                //账号
                AccountName: "",

                Page: 1,
                Size: 10,
                count: 0,

                list: [],
                loading: false,

                pickerOptions: {},

            }
        },

        computed: {
            searchObj: function () {
                return {
                    Page: this.Page,
                    Size: this.Size,
                    StatisticsType: this.StatisticsType,
                    PlatForm: this.PlatForm === "全部" ? "" : this.PlatForm,
                    DateTimeType: this.DateTimeType,
                    TimeStart: !_.isNil(this.dateRange) && Number(this.dateRange[0]) || "",
                    TimeEnd: !_.isNil(this.dateRange) && Number(this.dateRange[1]) || "",
                    AccountName: this.AccountName.trim(),
                }
            }
        },

        created: function () {
            let that = this;
            // 最大选择从昨天开始1年之前到数据
            this.pickerOptions.disabledDate = function (time) {
                if (that.DateTimeType === 0) {
                    let oneYearAgo = moment().subtract(1, 'days').subtract(2, 'month');
                    let yesterday = moment().subtract(1, 'days');
                    let curSelDate = moment(time);
                    return curSelDate > yesterday || curSelDate < oneYearAgo;
                }
            }
        },

        mounted: function () {
            this.getplatformList();
            this.search();
        },

        methods: {
            changeDateType(v) {
                this.dateRange = [];
                if (v === 0) {
                    this.formatUI="yyyy-MM-dd";
                    this.formatValue = "yyyyMMdd";
                } else {
                    this.formatUI="yyyy-MM";
                    this.formatValue = "yyyyMM";
                }

            },
            searchQuery() {
                if(this.searchObj.TimeStart==="" || this.searchObj.TimeEnd===""){
                    this.$message({
                        type: "warning",
                        offset: 300,
                        message: "请选择时间"
                    });
                    return;
                }
                this.Page = 1;
                this.search();
            },
            // 查询
            search: function () {
                let that = this;
                that.loading = true;

                service({
                    method: "get",
                    url: Api.statistics_account,
                    params: that.searchObj
                }).then(function (res) {
                    that.count = res.count;
                    that.list = res.data;
                    that.loading = false;
                })
            },

            indexMethod: function (index) {
                return index + 1 + (this.Page-1)*this.Size;
            },
            // 导出
            exportTaskExcel: function () {
                let qs = $.param({...this.searchObj, Size: this.count});
                let url = config.apiPath + Api.statistics_export + "?" + qs;

                window.open(url)
            },
            // 平台列表
            getplatformList() {
                service({
                    method: "get",
                    url: Api.mymedia_platform_getlist,
                    params: {
                        page: 1,
                        size: 1000,
                    }
                }).then((res) => {
                    this.platformList = [{"_id": "0", "name": "全部"}].concat([], res.data);
                });
            },
        }
    }
</script>

<style>
    .mclear-icon {
        display:none;
    }
</style>
